Repository CS3219-AY2223S1/cs3219-project-ay2223s1-g59, pull requests merged in 2022-10, with the labels that each got.

#26 Add search page and interview page functionality in frontend
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/HomePage.js
  frontend/src/components/InterviewPage.js
  frontend/src/components/SearchPage.js
  frontend/src/services/matchingService.js
Labels: enhancement

#23 Add Jwt token feature and frontend support
  frontend/src/App.js
  frontend/src/components/AlertMessage.js
  frontend/src/components/HomePage.js
  frontend/src/components/LoginPage.js
  frontend/src/components/NavBar.js
  frontend/src/components/SettingsPage.js
  frontend/src/components/SignupPage.js
  frontend/src/index.css
  frontend/src/services/userService.js
  user-service/controller/user-controller.js
  user-service/index.js
  user-service/middleware/auth.js
  user-service/routes/user-routes.js
Labels: enhancement

#30 Add matching service unit tests and GH Actions workflow
  .github/workflows/matching-service.yml
  matching-service/controllers/matchController.js
  matching-service/index.js
  matching-service/package-lock.json
  matching-service/package.json
  matching-service/test/test.js
  matching-service/test/testData.js
Labels: enhancement

#32 [Database Seeder] Add question collection seeder if collection is empty for LOCAL/DOCKER mongoDB.
  question-service/common/constants.js
  question-service/index.js
  question-service/questionSeeder.js
Labels: enhancement

#40 Add dockerignore file to question service
  question-service/.dockerignore
Labels: hacktoberfest-accepted

#49 Chat service backend and Chatbox component
  chat-service/index.js
  chat-service/package-lock.json
  chat-service/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/Chat.js
  frontend/src/components/InterviewPage.js
  frontend/src/configs.js
  frontend/src/index.css
Labels: enhancement

#61 Add docker files for Chat service
  chat-service/.dockerignore
  chat-service/dockerfile
  docker-compose.backend.yml
  docker-compose.yml
Labels: enhancement, hacktoberfest-accepted
