Repository CS3219-AY2223S1/cs3219-project-ay2223s1-g59, pull requests merged in 2022-11, with the labels that each got.

#66 Cleanup user-service
  README.md
  frontend/src/configs.js
  user-service/common/constants.js
  user-service/common/logger.js
  user-service/controller/user-controller.js
  user-service/index.js
  user-service/middleware/auth.js
  user-service/model/blacklist-orm.js
  user-service/model/blacklist.js
  user-service/model/repository.js
  user-service/model/user-orm.js
  user-service/model/user.js
  user-service/routes/user-routes.js
  user-service/test/test.js
Labels: enhancement

#68 Interview page UI change
  frontend/src/components/Chat.js
  frontend/src/components/CodeEditor.js
  frontend/src/components/InterviewPage.js
  frontend/src/components/LoginPage.js
  frontend/src/components/SignupPage.js
  frontend/src/index.css
Labels: enhancement

#75 Collab fix using redis
  .github/workflows/collaboration-service.yml
  .gitignore
  collaboration-service/common/constants.js
  collaboration-service/index.js
  collaboration-service/package-lock.json
  collaboration-service/package.json
  collaboration-service/test/test.js
  collaboration-service/test/testData.js
  docker-compose.backend.yml
  docker-compose.yml
Labels: bug

#78 Chat leave message and UI improvements
  chat-service/index.js
  chat-service/test/test.js
  frontend/src/components/HistoryPage.js
  frontend/src/components/InterviewPage.js
  frontend/src/components/SettingsPage.js
  frontend/src/index.css
Labels: enhancement

#77 Minor changes
  docker-compose.yml
  frontend/src/components/InterviewPage.js
  frontend/src/components/SearchPage.js
  frontend/src/services/userService.js
  user-service/controller/user-controller.js
  user-service/routes/user-routes.js
  user-service/test/test.js
Labels: enhancement

#81 Delete history when user deletes account
  frontend/src/components/HistoryPage.js
  frontend/src/components/HomePage.js
  frontend/src/components/LoginPage.js
  frontend/src/components/SettingsPage.js
  frontend/src/components/SignupPage.js
  frontend/src/services/historyService.js
Labels: enhancement

#83 Add UML diagrams for user-service
  docs/sequence-diagrams/user-service-change-password.puml
  docs/sequence-diagrams/user-service-delete-account.puml
  docs/sequence-diagrams/user-service.puml
Labels: documentation
